backend:
  name: github
  repo: amiegrrl/we-wear-eco # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

# when using the default proxy server port
local_backend: true

collections:
  - name: "brands"
    label: "Brands"
    folder: "_brands/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", hint: "Enter link without protocol (http://, https://)", widget: "string"}
      #- {label: "Tags", name: "tags", widget: "list"}
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "tags"
        searchFields: ["title", "link"]
        valueField: "title"
        displayFields: ["title"]
        multiple: true
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "tags"
    label: "Tags"
    folder: "_tags/"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tag", name: "tag", widget: "string", required: false}

  - label: "Tag Menu"
    name: "tagMenu"
    editor:
        preview: false
    files:
    - file: "_data/tagMenu.yml"
      label: "Tag Meu"
      name: "tagMenu"
      fields:
        - label: "Menu Items"
          name: "menuItems"
          widget: "list"
          fields: 
            - label: "Menu Item"
              name: "menuItem"
              widget: "relation"
              collection: "tags"
              searchFields: ["title", "tag"]
              valueField: "title"
              displayFields: ["title"]